import Layout from "/components/layout";
import Head from "next/head";
import CardPost from "/components/blogComponents/cardPost";
import FeaturedPost from "/components/blogComponents/Featuredpost";


export default function Home() {
     return (
          <>
               <Head>
                    <title>blog</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
               </Head>
               <Layout>
                    <div>
                         <FeaturedPost />
                         <CardPost />
                    </div>
               </Layout>
          </>
     );
}